# Generated by Django 4.1.3 on 2023-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('lang', models.CharField(max_length=255)),
                ('star', models.IntegerField(default=0)),
                ('star_by_span', models.IntegerField(default=0)),
                ('fork', models.IntegerField(default=0)),
            ],
        ),
    ]
